# Generated by Django 2.2.9 on 2020-02-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20200207_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_auth',
            field=models.BooleanField(default=False, verbose_name='是否认证'),
        ),
    ]
