# Generated by Django 2.2.9 on 2020-02-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_teacher_is_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='recom_stars',
            field=models.IntegerField(choices=[(0, '0'), (1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=0, verbose_name='推荐指数'),
        ),
    ]
