# Generated by Django 2.2.9 on 2020-02-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
